#!/bin/bash

cd "$(dirname "$0")"

if [ ! -d ".venv" ]; then
  echo "Please run install.sh first"
  exit 1
fi

source .venv/bin/activate
pip install --no-cache-dir -U -r requirements.txt
exec python3 proxy.py
deactivate
